name: Node.js CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'products/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'products/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Correctly setting working directory for npm ci (or npm install)
      - name: Install dependencies
        run: npm ci
        working-directory: ./products

      - name: Build
        run: npm run build --if-present
        working-directory: ./products

      - name: Run tests
        run: npm test
        working-directory: ./products
